### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by pra2304tik** [GTCG/PY4E#1]
AttributeError: module 'urllib' has no attribute 'urlopen'

**Comment by valavb** [comment]
If you are using python 3 then you must use 
`urllib.request.urlopen()`  instead of `urllib.urlopen()`

**Comment by yash-badani** [comment]
Yes I am facing the same issue

**Comment by yash-badani** [comment]
try writing urllib.request.urlopen(url) instead of urllib.urlopen at every place..it might work out

**Comment by pra2304tik** [comment]
or instead you can import as: from urllib.request import urlopen and then
open as  x=urlopen(url)  it'll work definately :)<3

**Comment by GTCG** [comment]
@pra2304tik : I fixed this issue last week. I've been re-testing all these scripts and this issue has now also been fixed.
Happy programming!
